export const ADD_REGISER_DATA = "ADD_REGISER_DATA"
export const ADD_REAUTH_DATA = "ADD_REAUTH_DATA"
export const LOGOUT_USER = "LOGOUT_USER"
export const ADD_WIDTH = "ADD_WIDTH"
export const ADD_MONEY = "ADD_MONEY"
export const ADD_CLAIMED = "ADD_CLAIMED"

export const OVERFLOW_HIDDEN = "OVERFLOW_HIDDEN"
export const OVERFLOW_AUTO = "OVERFLOW_AUTO"

export const SET_DEVICE_PHONE = "SET_DEVICE_PHONE"